### ISSUE TITLE
Roadmap for this great app

### ISSUE THREAD

**Issue by Salmon-Bard** [franknyarkoh/bookings#1]
I'm so happy to find that there is a true effort to provide a hotel management app above the very minimum basic app the comes with ERPNext.

I'm coming from Odoo and used their community opensource hotel management system app which covers realword business requirements with extendable functionalities and features in mind. 
Here is a demo install of odoo hotel Mantegna app which can be an inspiration 
for this porject: 
http://3379265-12-0-890ad1.runbot1.odoo-community.org/web?model=hotel.reservation
**(username & password: admin)**

I would like to help progress this project, but unfortunately my coding skills are not to the task in frappe and python in general. Where I can help in testing and documentation. 

If there is a roadmap it will be very easy to start the process and gain attraction and momentum to push forward. We can use odoo app as a reference since it has slimier structure to ERPNext modules.

**Comment by franknyarkoh** [comment]
Thanks Salmon. I will definitely check it out

**Comment by ukwuezeobinna** [comment]
Login details don't work
